Add members and description to gh frontpage
BiAPoL/.github pull request #2
Opened 2024-04-10 11:44 UTC by jo-mueller

2024-04-11 11:31 UTC, stefanhahmann requested changes
In general I am happy with the contents. I suggested some minor changes, including typos and different url.

2024-04-11 11:31 UTC, stefanhahmann commented on profile/README.md
> +Welcome to the profile of the bio-image analysis technology development group (BiAPoL) at [Physics of Life](https://physics-of-life.tu-dresden.de/). We provide services and tools for the analysis of
```suggestion
Welcome to the profile of the bio-image analysis technology development group (BiAPoL) at [Physics of Life / TU Dresden](https://physics-of-life.tu-dresden.de/). We provide services and tools for the analysis of microscopy images in the life sciences. If you have any questions or need help with image analysis, feel free to contact us (see contact information below).
```

2024-04-11 11:31 UTC, stefanhahmann commented on profile/README.md
> +We are currently three postodcs and one student working in the group:
```suggestion
We are currently three postdocs and one student working in the group:
```

2024-04-11 11:31 UTC, stefanhahmann commented on profile/README.md
> +For more information on our current and previous members and our mission, visit our [group page](https://physics-of-life.tu-dresden.de/). For requests, please contact us via email (biapol at tu-dresd
```suggestion
For more information on our current and previous members and our mission, visit our [group page](https://physics-of-life.tu-dresden.de/research/core-groups/bio-image-analysis). For requests, please contact us via email (biapol (at) tu-dresden.de). For image analysis questions, please make sure to also check the image analysis [forum](https://forum.image.sc/).
```

2024-04-11 12:22 UTC, jo-mueller commented
Thanks for the review @stefanhahmann :)

2024-04-12 13:26 UTC, zoccoler approved these changes

2024-04-12 13:33 UTC, zoccoler commented
I suggest just to add some white background to the consultation icon, because on the github dark theme, it is not well displayed.

2024-04-12 14:04 UTC, jo-mueller commented
@zoccoler fixed 👍

2024-04-12 15:07 UTC, zoccoler commented
> @zoccoler fixed 👍

Looks fine now!

2024-04-15 06:23 UTC, jo-mueller commented
@maleehahassan any comments on this?

2024-04-15 11:58 UTC, maleehahassan commented
@jo-mueller Looks nice. I was thinking of slipping a brief description of the group into the readme section. What do you think?

2024-04-15 12:29 UTC, jo-mueller commented
> Looks nice. I was thinking of slipping a brief description of the group into the readme section. What do you think?
> 
> 

@maleehahassan Send a pull request to my pull request :)

2024-04-18 13:53 UTC, merged